#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "http://localhost/local/default.git"

strains:
  - name: default
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
